version: "3"

volumes:
  gem_cache:

services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - gem_cache:/usr/src/gems
    env_file:
      - .env/development/app.env
    tty: true
    stdin_open: true
